version: '3.0'

services:
  server:
    container_name: server
    build:
      context: .
    env_file:
      - .env.dev
    volumes:
      - .:/server
    ports:
      - 5000:5000
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env.dev
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: