version: '3.0'

services:
  server:
    container_name: dev-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/server
    ports:
      - 5000:5000
    command: npm run dev

    restart: always