version: '3.0'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/server
    ports:
      - 5000:5000
    command: npm run start:prod
    restart: always